name: Casket Gitea CI
run-name: ${{ gitea.actor }} runs CI for casket
on: 
  push:
    branches:
      - master

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/abel2333/casket-ci:latest

    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v6

      - name: Run unit tests
        run: cargo test
